export const english = {
  countryCode: "en-US",
  sign_in_email_placeholder: "Email",
  sign_in_password_placeholder: "Password",
  sign_in_login_button: "Login",
  sign_in_signup_button: "Sign Up",
  sign_in_email_required: "Email is required",
  sign_in_email_invalid: "Please enter a valid email",
  sign_in_password_required: "Password is required",
  sign_in_password_min_length: "Password must be at least 6 characters",
  sign_in_error_user_not_found: "User not found",
  sign_in_error_invalid_credential: "Wrong email or password",
  sign_in_error_default: "An error occurred during sign-in",

  sign_up_username_placeholder: "User Name",
  sign_up_email_placeholder: "Email",
  sign_up_password_placeholder: "Password",
  sign_up_create_account_button: "Create New Account",
  sign_up_goto_signin_button: "Go To Sign In",
  sign_up_username_required: "User name is required",
  sign_up_username_min_length: "User name must be more than 5 characters",
  sign_up_email_invalid: "Email is wrong",
  sign_up_email_required: "Email is required",
  sign_up_password_required: "Password is required",
  sign_up_password_min_length: "Password must be at least 6 characters",
  sign_up_success: "User Created",
  sign_up_error_email_in_use:
    "This email is already in use! you can't use this email",
  sign_up_error_invalid_email: "The email address is invalid.",
  sign_up_error_weak_password: "The password is too weak.",
  sign_up_error_default: "An error occurred during sign-up.",

  tab_home: "Home",
  tab_cart: "Cart",
  tab_profile: "Profile",

  cart_continue_button: "Continue",
  cart_checkout_screen: "CheckoutScreen",

  empty_cart_title: "Your Cart Is Empty",
  empty_cart_subtitle: "Browse our products and find something you like.",
  start_shopping: "Start Shopping",

  checkout_fullname_placeholder: "Full Name",
  checkout_phone_placeholder: "Phone Number",
  checkout_address_placeholder: "Detailed Address",
  checkout_confirm_button: "Confirm",
  checkout_name_required: "Name is required",
  checkout_name_min_length: "Name must be at least 3 characters",
  checkout_phone_required: "Phone number is required",
  checkout_phone_digits: "Must be only digits",
  checkout_phone_min_length: "Phone number must be at least 11 digits",
  checkout_address_required: "Address is required",
  checkout_address_min_length:
    "Please provide a detailed address with at least 15 characters",
  checkout_success_message: "Order Placed Successfully",
  checkout_error_message: "Error Happened",

  profile_my_orders: "My Orders",
  profile_language: "Language",
  profile_logout: "Logout",
  profile_welcome: "Welcome {{userName}}",

  totals_items_price: "Items Price:",
  totals_taxes: "Taxes:",
  totals_shipping_fee: "Shipping Fee:",
  totals_order_total: "Order Total:",
  totals_currency: "USD",

  order_details_title: "Order Details:",
  order_total_price: "Total Price:",
  order_date: "Date:",
  change_language: `Change your Language`,
  good_morning: "Good Morning",
  good_afternoon: "Good Afternoon",
  good_evening: "Good Evening",
  good_night: "Good Night",
  empty_order_title: "Your Order Is Empty",
};

export const dutch = {
  countryCode: "de",
  sign_in_email_placeholder: "E-Mail",
  sign_in_password_placeholder: "Passwort",
  sign_in_login_button: "Anmelden",
  sign_in_signup_button: "Registrieren",
  sign_in_email_required: "E-Mail ist erforderlich",
  sign_in_email_invalid: "Bitte geben Sie eine gültige E-Mail-Adresse ein",
  sign_in_password_required: "Passwort ist erforderlich",
  sign_in_password_min_length: "Passwort muss mindestens 6 Zeichen lang sein",
  sign_in_error_user_not_found: "Benutzer nicht gefunden",
  sign_in_error_invalid_credential: "Falsche E-Mail oder Passwort",
  sign_in_error_default: "Beim Anmelden ist ein Fehler aufgetreten",

  sign_up_username_placeholder: "Benutzername",
  sign_up_email_placeholder: "E-Mail",
  sign_up_password_placeholder: "Passwort",
  sign_up_create_account_button: "Neues Konto erstellen",
  sign_up_goto_signin_button: "Zur Anmeldung",
  sign_up_username_required: "Benutzername ist erforderlich",
  sign_up_username_min_length: "Benutzername muss mehr als 5 Zeichen lang sein",
  sign_up_email_invalid: "E-Mail ist ungültig",
  sign_up_email_required: "E-Mail ist erforderlich",
  sign_up_password_required: "Passwort ist erforderlich",
  sign_up_password_min_length: "Passwort muss mindestens 6 Zeichen lang sein",
  sign_up_success: "Benutzer erstellt",
  sign_up_error_email_in_use:
    "Diese E-Mail wird bereits verwendet! Sie können diese E-Mail nicht verwenden",
  sign_up_error_invalid_email: "Die E-Mail-Adresse ist ungültig",
  sign_up_error_weak_password: "Das Passwort ist zu schwach",
  sign_up_error_default: "Bei der Registrierung ist ein Fehler aufgetreten",

  tab_home: "Startseite",
  tab_cart: "Warenkorb",
  tab_profile: "Profil",

  cart_continue_button: "Weiter",
  cart_checkout_screen: "Zur Kasse",

  empty_cart_title: "Ihr Warenkorb ist leer",
  empty_cart_subtitle:
    "Durchstöbern Sie unsere Produkte und finden Sie etwas, das Ihnen gefällt",
  start_shopping: "Jetzt einkaufen",

  checkout_fullname_placeholder: "Vollständiger Name",
  checkout_phone_placeholder: "Telefonnummer",
  checkout_address_placeholder: "Vollständige Adresse",
  checkout_confirm_button: "Bestätigen",
  checkout_name_required: "Name ist erforderlich",
  checkout_name_min_length: "Name muss mindestens 3 Zeichen lang sein",
  checkout_phone_required: "Telefonnummer ist erforderlich",
  checkout_phone_digits: "Darf nur Ziffern enthalten",
  checkout_phone_min_length:
    "Telefonnummer muss mindestens 11 Ziffern lang sein",
  checkout_address_required: "Adresse ist erforderlich",
  checkout_address_min_length:
    "Bitte geben Sie eine detaillierte Adresse mit mindestens 15 Zeichen ein",
  checkout_success_message: "Bestellung erfolgreich aufgegeben",
  checkout_error_message: "Ein Fehler ist aufgetreten",

  profile_my_orders: "Meine Bestellungen",
  profile_language: "Sprache",
  profile_logout: "Abmelden",
  profile_welcome: "Willkommen {{userName}}",

  totals_items_price: "Artikelpreis:",
  totals_taxes: "Steuern:",
  totals_shipping_fee: "Versandkosten:",
  totals_order_total: "Gesamtbetrag:",
  totals_currency: "EUR",

  order_details_title: "Bestelldetails:",
  order_total_price: "Gesamtpreis:",
  order_date: "Datum:",
  change_language: `Taal wijzigen`,
  good_morning: "Goedemorgen",
  good_afternoon: "Goedemiddag",
  good_evening: "Goedenavond",
  good_night: "Goedenacht",
  empty_order_title: "Ihr Warenkorb ist leer",
};

// change_language: (count: number) =>
//     `Change your Language  with ${count} notification${count !== 1 ? "s" : ""}`,
